name: PluginUpdater-WB
version: 26.1.2-1.0.2-dev1
main: me.webbeck.pluginUpdater.PluginUpdater
api-version: "26.1"
author: WebBeck
description: Highly advanced, fully asynchronous plugin manager and updater for Paper.

commands:
  updater:
    description: Main command for PluginUpdater-WB
    usage: /<command> <help|-v|check|run|list|reload|plugin>
    aliases: [upd]

permissions:
  pluginupdater.admin:
    description: Allows full access to the updater commands.
    default: op